--BT1--
-- Câu 1 --
Create view DSSV
AS
	SELECT MSSV, TENSV,  SODT, LOP, DIACHI
	FROM SINHVIEN
GO 

SELECT *FROM DSSV

-- Câu 3 --
GO
Create view DSGVPB
as
	select TENGV,TENHV,TENHH, SODT, DIACHI
	FROM GIAOVIEN GV, GV_HV_CN GHC, HOCVI HV, HOCHAM HH
	WHERE GV.MSGV= GHC.MSGV AND GHC.MSHV= HV.MSHV AND GV.MSHH = HH.MSHH
GO
SELECT * FROM DSGVPB


--bt2--
--Cau 1--
GO
create view TK_HD_DT
as
	select TENGV, MSDT
	FROM GIAOVIEN G, GV_HDDT H
	WHERE G.MSGV=H.MSGV
GO
SELECT* FROM TK_HD_DT

--cau3--

go
create view TK_DIEM
as
	select TENDT, H.DIEM DIEM_HD, P.DIEM DIEM_PB, U.DIEM DIEM_UV
	from DETAI D, GV_HDDT H, GV_PBDT P, GV_UVDT U
	WHERE D.MSDT=H.MSDT AND D.MSDT=P.MSDT AND D.MSDT=U.MSDT
GO
SELECT * FROM TK_DIEM

--cau 5--
GO
create view SL_GV_HV
AS
	SELECT TENHV, MSGV
	FROM HOCVI H, GV_HV_CN G
	WHERE H.MSHV=G.MSHV
GO
SELECT * FROM SL_GV_HV

--cau 6--
GO
create view SL_GV_CN
AS
	SELECT TENCN, MSGV
	FROM CHUYENNGANH C, GV_HV_CN G
	WHERE C.MSCN=G.MSCN
GO
SELECT * FROM SL_GV_CN

--CAU 7--

GO 
CREATE VIEW TK_HDDT
AS
	SELECT TENGV, H.MSDT, MSSV
	FROM GIAOVIEN G, GV_HDDT H, SV_DETAI S
	WHERE G.MSGV=H.MSGV AND H.MSDT=S.MSDT
GO
SELECT * FROM TK_HDDT